export const TeamMembers = [
  {
    id: 1,
    username: "John Doe",
    Post: "Project Manager",
    active: "Online",
    department: "Management",
    activetask: 5,
    Completed: 23,
  },
  {
    id: 2,
    username: "Sarah Smith",
    Post: "Frontend Developer",
    active: "Offline",
    department: "Development",
    activetask: 3,
    Completed: 18,
  },
  {
    id: 3,
    username: "Michael Lee",
    Post: "UI Designer",
    active: "Away",
    department: "Design",
    activetask: 4,
    Completed: 20,
  },
  {
    id: 4,
    username: "Emma Brown",
    Post: "QA Engineer",
    active: "Online",
    department: "Quality Assurance",
    activetask: 2,
    Completed: 15,
  },
  {
    id: 5,
    username: "David Wilson",
    Post: "Backend Developer",
    active: "Busy",
    department: "Development",
    activetask: 6,
    Completed: 30,
  },
  {
    id: 6,
    username: "Olivia Martinez",
    Post: "Operations Manager",
    active: "Online",
    department: "Operations",
    activetask: 3,
    Completed: 19,
  },
  {
    id: 7,
    username: "James Anderson",
    Post: "Graphic Designer",
    active: "Offline",
    department: "Design",
    activetask: 2,
    Completed: 14,
  },
  {
    id: 8,
    username: "Sophia Taylor",
    Post: "QA Analyst",
    active: "Away",
    department: "Quality Assurance",
    activetask: 5,
    Completed: 22,
  },
  {
    id: 9,
    username: "Daniel Thomas",
    Post: "DevOps Engineer",
    active: "Online",
    department: "Operations",
    activetask: 4,
    Completed: 25,
  },
  {
    id: 10,
    username: "Isabella White",
    Post: "Team Lead",
    active: "Busy",
    department: "Management",
    activetask: 3,
    Completed: 28,
  },
];
